server:
  port: 8920
  compression:
    enabled: true

spring:
  profiles:
    active: dev
  freemarker:
    cache: false
    charset: utf-8
    settings:
      classic_compatible: false
      whitespace_stripping: true
      template_update_delay: 1
      number_format: 0.######
      date_format: yyyy-MM-dd
      template_exception_handler: rethrow
  http:
    encoding:
      charset: UTF-8


spring.jaxway.filter.enable: true



#开启feign的GZIP压缩
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
  hystrix:
    enabled: true
  httpclient:
    enabled: true

mybatis:
  type-aliases-package: com.gateway.jaxway.admin.dao.model
  mapper-locations: classpath*:mapping/*.xml
  configuration:
    cache-enabled: true

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/JaxwayDB?allowMultiQueries=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    #password: "93ae8276270448d688e4a427cf765cb5"
    lettuce:
      pool:
        min-idle: 1
        max-wait: 3000ms
    cluster:
      maxRedirects: 5
      nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384

---

spring:
  profiles: test



---


spring:
  profiles: prod




---